name: Publish on releases

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 8

      - name: Gradle build cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-build-

      - name: Gradle wrapper cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Publish plugin to Gradle Portal
        run: ./gradlew publishPlugins -Pversion=${{ github.event.release.tag_name }} -Pgradle.publish.key=${{ secrets.GRADLE_API_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_API_SECRET }}
